// --- Creating a Custom Component ---
//
// A React component is a regular JavaScript function with two conventions:
//   1. Its name starts with an UPPERCASE character (e.g., Post, not post).
//      This is optional where you define the function, but required where
//      you use it in JSX. In JSX, lowercase names (div, p, h1…) are treated
//      as built-in HTML elements, while uppercase names (Post, App…) are
//      treated as custom components. If you used <post> instead of <Post>,
//      React would look for a native HTML element called "post" — which
//      doesn't exist — rather than executing your component function.
//   2. It returns JSX code — the HTML-like markup that describes what this
//      piece of the UI should look like.
//
// Component files are typically placed in a "components" folder inside src/.
// The folder name is a convention, not a requirement. The .jsx file extension
// IS required in Vite projects so the build tool knows the file contains JSX.
// (Create React App projects also accept plain .js for JSX files.)

// --- Importing CSS Modules ---
//
// When importing a .module.css file, you use a named import (here called
// "classes") rather than a bare side-effect import like "import './file.css'".
// The named import gives you a JavaScript object whose keys are the class
// names defined in the CSS file (post, author, text) and whose values are
// the unique, transformed class names generated by the build tool.
import classes from './Post.module.css';

// This Post component represents a single post (tweet-like item) in the
// demo application.
//
// --- Props (Properties) ---
//
// Props are React's mechanism for passing data from a parent component
// into a child component — similar to how you pass arguments to a regular
// JavaScript function. The difference is that with components, you set
// the values using HTML-attribute-like syntax in JSX (e.g.,
// <Post author="Max" body="Hello" />) and React collects ALL of those
// custom attributes into a single object that it passes as the first
// (and only) parameter of your component function.
//
// The parameter is conventionally named "props", but the name is your
// choice. Whatever custom attribute names you set on the component
// (author, body, etc.) become keys on this object, so you access them
// as props.author, props.body, and so on.
//
// Not every component needs props — some components are self-contained
// and always render the same content. But props are essential whenever
// you want to reuse a component with different data (e.g., different
// post authors and text coming from a database).
//
// A component function is still a regular JavaScript function — you can
// run any standard JavaScript code inside it (variables, calculations,
// API calls, etc.) before the return statement. The only requirement is
// that the function ultimately returns JSX.
function Post(props) {
  // --- Dynamic values in JSX with curly braces ---
  //
  // Wrapping a JavaScript expression in single curly braces { } inside
  // JSX tells React to evaluate that expression and output its result.
  // Without curly braces, text is rendered literally (e.g., "props.author"
  // would appear as the string "props.author"). With curly braces, React
  // evaluates the expression and inserts its current value instead.
  //
  // You can place any valid JavaScript expression inside the braces:
  // variables, constants, arithmetic ({2 + 2} renders "4"), function
  // calls, ternary operators, property access (props.author), etc.
  // This is how you make React UIs dynamic — whether displaying prop
  // values, computed results, or data fetched from a backend API.
  // --- className (not class) ---
  //
  // In JSX, CSS classes are assigned with the "className" attribute, not
  // "class". This is because "class" is a reserved keyword in JavaScript.
  // Here we use the classes object from the CSS Module import, accessing
  // its properties (classes.post, classes.author, classes.text) to get
  // the unique, scoped class names generated by the build tool.
  return (
    <div className={classes.post}>
      <p className={classes.author}>{props.author}</p>
      <p className={classes.text}>{props.body}</p>
    </div>
  );
}

// The component must be exported so other files can import and use it.
// Using "export default" means the importing file can choose any name for
// the import, though by convention the same name is used (Post).
export default Post;
